// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wallet.Models;

namespace wallet.Migrations
{
    [DbContext(typeof(WalletContext))]
    partial class WalletContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("wallet.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1
                        },
                        new
                        {
                            UserId = 2
                        });
                });

            modelBuilder.Entity("wallet.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Sum")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "USD",
                            Sum = 2000m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Currency = "EUR",
                            Sum = 5000m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Currency = "GBP",
                            Sum = 50000m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Currency = "USD",
                            Sum = 0m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Currency = "EUR",
                            Sum = 20000m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Currency = "GBP",
                            Sum = 56000m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("wallet.Models.Wallet", b =>
                {
                    b.HasOne("wallet.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
